apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-s3-deployment
  namespace: test
  labels:
    app: spring-s3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-s3
  template:
    metadata:
      labels:
        app: spring-s3
    spec:
      serviceAccountName: pod-sa
      containers:
        - name: spring-s3
          image: 056206897674.dkr.ecr.eu-west-1.amazonaws.com/spring-s3:latest
          ports:
            - containerPort: 80
          env:
            - name: AWS_REGION
              value: eu-west-1
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
